In [2]:
import numpy as np

In [27]:
a = np.array([[3,2224,6,5,1,3], [1,2,3,2,4,5]], dtype='int16')
print(a)

[[   3 2224    6    5    1    3]
 [   1    2    3    2    4    5]]


In [11]:
a.ndim

2

In [12]:
a.shape

(2, 3)

In [15]:
a.dtype

dtype('int8')

In [21]:
a.nbytes

6

In [22]:
a[1,2]

3

In [23]:
a[:, 1:]

array([[4, 6],
       [2, 3]], dtype=int8)

In [25]:
a[:, 1:5:2]

array([[4, 5],
       [2, 2]], dtype=int8)

In [42]:
z = np.zeros((2,2))
ones = np.ones((2,4), dtype = 'int8')
f = np.full((3,4), 69)
fl = np.full_like(f, 420)

In [43]:
fl

array([[420, 420, 420, 420],
       [420, 420, 420, 420],
       [420, 420, 420, 420]])

In [51]:
np.random.rand(5,2) #random decimal nums
np.random.randint(8, 69, size=(5,2)) #random int nums

array([[14, 48],
       [50, 36],
       [52, 59],
       [48, 55],
       [34, 44]])

In [53]:
np.identity(4, dtype='int8')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [65]:
np.repeat(np.array([[1,2,3]]), 5, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [73]:
#challenge at 31:55
one = np.ones((5,5), dtype='int32')
one[1:4, 1:4] = np.zeros((3,3))
one[2,2] = 9

In [74]:
one

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [75]:
###Be careful when copying the array!

In [78]:
a = np.array([1,2,3])
b = a  #use .copy -- b = a.copy()
print(a)
b[0] = 69
print(a)

[1 2 3]
[69  2  3]


In [79]:
####Some MATH

In [80]:
a

array([69,  2,  3])

In [81]:
a + 2 

array([71,  4,  5])

In [84]:
a += 2
a

array([75,  8,  9])

In [85]:
a/48

array([1.5625    , 0.16666667, 0.1875    ])

In [89]:
(a/45).dtype

dtype('float64')

In [92]:
np.sin(a)
np.cos(a)

array([ 0.92175127, -0.14550003, -0.91113026])

#### Linear Algebra!

In [93]:
a = np.full((2,3), 4)
b = np.full((3,4), 5)

In [94]:
np.matmul(a,b)

array([[60, 60, 60, 60],
       [60, 60, 60, 60]])

In [97]:
np.linalg.det(np.identity(3))

1.0

### Statistics!

In [99]:
stats = np.array([[1,3,5], [2,4,6]])

In [103]:
np.min(stats, axis=0)

array([1, 3, 5])

In [105]:
np.max(stats, axis=1)

array([5, 6])

In [107]:
np.sum(stats)
np.sum(stats, axis = 0)

array([ 3,  7, 11])

### Reorganizing stuff - hstack, vstack

In [114]:
a = np.array([[1,2,3,4], [4,5,6,8]])

In [113]:
a.reshape((1,8))

array([[1, 2, 3, 4, 4, 5, 6, 8]])

In [118]:
#vertical stack vectors
np.vstack([a[0,:],a[0,:],a,a[0,:]])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [4, 5, 6, 8],
       [1, 2, 3, 4]])

In [119]:
np.hstack([a,a])

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [4, 5, 6, 8, 4, 5, 6, 8]])

### Reading data from files

In [ ]:
filedata = np.genfromtxt('filename.txt', delimiter = ',')
filedata = filedata.astype('int8')

In [ ]:
np.any(filedata > 50, axis = 0)

In [138]:
i = np.array([1,2,3,4,5])
a = np.vstack((i,i+5,i+10,i+15,i+20,i+25))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [136]:
a[((a % 6 == 2) & (a <= 20))]

array([ 2,  8, 14, 20])

In [137]:
a[[1,2,3,4], [1,2,3,4]]

array([ 7, 13, 19, 25])

In [143]:
a[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])